---
deployment:
  tasks:
    - export DEPLOYPATH=/home/datangle/home/
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
